@hostname = localhost
GET /api/HttpExample
Host: {{hostname}}:7071
User-Agent: curl/7.64.1
Content-Type: application/json

###
GET /api/HttpExample
Host: {{hostname}}:7071
User-Agent: curl/7.64.1
Content-Type: application/json